version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.1
  node: circleci/node@5.1.0
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Install AWS CDK
          command: npm install -g aws-cdk
      - aws-cli/setup
      - run:
          name: Bootstrap AWS CDK
          command: cdk bootstrap
      - run:
          name: Deploy AWS CDK Stack
          command: cdk deploy --require-approval never
workflows:
  deploy:
    jobs:
      - build