version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.1
  node: circleci/node@5.1.0
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION_NAME

      - checkout
      - run:
          name: 'install aws cdk'
          command: npm install --prefix=$HOME/.local --global aws-cdk
      - run:
          name: 'install ECS packages'
          command: |
            cd cdk && npm install
      - run:
          name: Bootstrap AWS CDK
          command: cdk bootstrap
      - run:
          name: Deploy AWS CDK Stack
          command: cdk deploy --require-approval never
workflows:
  deploy:
    jobs:
      - build